export enum Category {
    Programming = 'Programming',
    DataScience = 'Data Science',
    Technology = 'Technology',
    SelfImprovement = 'Self Improvement',
    Writing = 'Writing',
    Relationships = 'Relationships',
    MachineLearing = 'Machine Learning',
    Flutter = 'Flutter',
    ArtificialCorner = 'Artificial Corner',
    Productivity = 'Productivity',
    Politics = 'Politics',
    WhatWereReading = 'What Were Reading',
    Parenting = 'Parenting',
    Business = 'Business',
    Karate = 'Karate',
    Led = 'Led',
    Nonfiction = 'Nonfiction',
    BlackLivesMatter = 'BlackLivesMatter',
    Leadership = 'Leadership',
    BurningMan = 'Burning Man',
    Diversity = 'Diversity',
    WritingInEloquence = 'Writing In Eloquence',
    Geography = 'Geography',
    CareerBreak = 'Career Break',
    Communication = 'Communication',
    FinanceAndBanking = 'Finance And Banking'
}